spring:
  datasource:
    dynamic:
      datasource:
        master:
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://127.0.0.1:3306/cc-spring-demo-sys?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=Asia/Shanghai
          username: root
          password: ENC(Aj35A2YblMMdLBQ246t9KA==)
  redis:
    host: 127.0.0.1
    port: 6379
jasypt:
  encryptor:
    password: demo
cc-spring:
  common:
    microservice: false
  resource:
    signing-key: cc-spring
  auth:
    sys-user-service: local